job_boards = [
    "LinkedIn",
    "Indeed",
    "We Work Remotely",
    "Remote.co",
    "FlexJobs",
    "Remotive",
    "Himalayas",
    "Wellfound",
    "Dice",
    "Built In",
    "Jobspresso",
    "Working Nomads",
    "PowerToFly",
    "Greenhouse Job Board",
    "Otta",
]

excluded_companies = [
    # Big Tech
    "Amazon",
    "Microsoft",
    "Google",
    "Meta",
    "Apple",
    "Netflix",
    "Salesforce",
    "Oracle",
    "IBM",
    "SAP",
    "Dell",
    "HP",
    "Intel",
    "Cisco",
    "Nvidia",
    "Adobe",
    "Workday",
    "ServiceNow",
    "Snowflake",
    # Large Consulting
    "Accenture",
    "Deloitte",
    "McKinsey",
    "PwC",
    "KPMG",
    "EY",
    "Capgemini",
    "Infosys",
    "Wipro",
    "TCS",
]
